-- TABLE CREATION
CREATE TABLE IF NOT EXISTS HIRED_EMPLOYEES
(
    ID            INTEGER PRIMARY KEY,
    NAME          VARCHAR,
    DATETIME      VARCHAR,
    DEPARTMENT_ID INTEGER,
    JOB_ID        INTEGER
);
CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
    ID         INTEGER PRIMARY KEY,
    DEPARTMENT VARCHAR
);
CREATE TABLE IF NOT EXISTS JOBS
(
    ID  INTEGER PRIMARY KEY,
    JOB VARCHAR
);