-- TABLE CREATION
CREATE TABLE IF NOT EXISTS HIRED_EMPLOYEES
(
    ID            INT PRIMARY KEY,
    NAME          VARCHAR,
    DATETIME      varchar,
    DEPARTMENT_ID INT,
    JOB_ID        INTEGER
);
CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
    ID         INT PRIMARY KEY,
    DEPARTMENT VARCHAR
);
CREATE TABLE IF NOT EXISTS JOBS
(
    ID  INT PRIMARY KEY,
    JOB VARCHAR
);